[project]
name = "free-image"
version = "0.1.0"
description = "free-image"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "concurrent-log-handler>=0.9.28",
    "duckdb>=1.4.0",
    "fastapi>=0.136.1",
    "gradio>=6.13.0",
    "langgraph>=1.2.0",
    "matplotlib>=3.10.6",
    "modelscope>=1.36.3",
    "nvitop>=1.6.2",
    "openai>=1.65.4",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "tenacity>=9.1.4",
    "termcolor>=2.5.0",
    "tqdm>=4.67.1",
]

[tool.setuptools]
py-modules = []

